### ISSUE TITLE
Code Request for HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING

### ISSUE THREAD

**Issue by euiyulsong** [nbip/supMIWAE#1]
Dear authors,

This is EuiYul Song from KAIST. I am currently building an imputation model based on your model, HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING?. I try to implement your model on my own, but I am having a hard time implementing it. May I request your code for the above paper? Thank you for your understanding.

Sincerely,

EuiYul Song

**Comment by nbip** [comment]
The repo has been updated, with more experiments to come
