### ISSUE TITLE
The problem of   code for HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING

### ISSUE THREAD

**Issue by Qingmin2020** [nbip/supMIWAE#2]
Dear authors,
As the missing data problem is one very important subject, your work "HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING" provides us a new method . I am very interested with it,However when i implemented , i came across some difficulty.
Can you provide me your code? Many thanks.

**Comment by nbip** [comment]
The repo has been updated, with more experiments to come

**Comment by nbip** [comment]
Hi there,

The repo has been updated with model code and a single experiment, more experiments to come,

Best regards,
Niels

From: QM-zhang-sat ***@***.***>
Reply to: nbip/supMIWAE ***@***.***>
Date: Tuesday, 22 March 2022 at 16.08
To: nbip/supMIWAE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nbip/supMIWAE] The problem of code for HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING (Issue #2)


Dear authors,
As the missing data problem is one very important subject, your work "HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING" provides us a new method . I am very interested with it,However when i implemented , i came across some difficulty.
Can you provide me your code? Many thanks.

**Comment by Qingmin2020** [comment]
Hi，Niels
    thanks for sharing the code
Best wishes.
QM-Zhang
















At 2022-05-25 19:14:09, "Niels Bruun Ipsen" ***@***.***> wrote:

Hi there,

The repo has been updated with model code and a single experiment, more experiments to come,

Best regards,
Niels

From: QM-zhang-sat ***@***.***>
Reply to: nbip/supMIWAE ***@***.***>
Date: Tuesday, 22 March 2022 at 16.08
To: nbip/supMIWAE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nbip/supMIWAE] The problem of code for HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING (Issue #2)


Dear authors,
As the missing data problem is one very important subject, your work "HOW TO DEAL WITH MISSING DATA IN SUPERVISED DEEP LEARNING" provides us a new method . I am very interested with it,However when i implemented , i came across some difficulty.
Can you provide me your code? Many thanks.
